import type { Metadata } from "next";

import "./globals.css";
import ReactToast from "./ReactToast";
import ReactQueryProvider from "./ReactQueryProvider";
import { roboto } from "./fonts";
import ModalProvider from "./ModalProvider";
import Modal from "@/COMPONENTS/GLOBAL_COMPONENTS/Modal";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout( {children,}: Readonly<{ children: React.ReactNode;}>) {

  return (
    <html lang="en">
      <body className={`${roboto.className}  overflow-x-hidden h-fit  ` } >
          
          <ReactQueryProvider>
            <ReactToast/>

            <ModalProvider>
              <Modal/>
              {children}
            </ModalProvider>


          </ReactQueryProvider>
         

        </body>
    </html>
  );

}
